name: Deploy website to Heroku
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initi project
        uses: actions/checkout@v2
      - name: PHP Linter
        uses: michaelw90/PHP-Lint@master
      - name: Sercurity checker
        uses: symfonycorp/security-checker-action@v2
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse src/