name: Deploy website to Heroku
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      # git clone
      - uses: actions/checkout@v2
      #linter
      - uses: michaelw90/PHP-Lint@master